import { readFileSync, writeFileSync, readdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const LOCALES_DIR = join(ROOT, "locales");
const OUTPUT = join(ROOT, "src", "strings.ts");

const files = readdirSync(LOCALES_DIR).filter(f => f.endsWith(".json"));
const all = {};

for (const file of files) {
	const lang = file.replace(".json", "");
	const content = readFileSync(join(LOCALES_DIR, file), "utf-8");
	all[lang] = JSON.parse(content);
}

const langs = Object.keys(all);
const keys = Object.keys(all[langs[0]]);
const langUnion = langs.map(l => `"${l}"`).join(" | ");

let output = `// Auto-generated by scripts/generate-strings.mjs. Do not edit.
// Run \`npm run build:strings\` to regenerate.

const strings: Record<string, Record<string, string>> = ${JSON.stringify(all, null, 2)};

export type Lang = ${langUnion};

export function t(key: string, lang: Lang): string {
	return strings[lang]?.[key] ?? strings["zh-CN"]?.[key] ?? key;
}

export function langStrings(lang: Lang): Record<string, string> {
	return strings[lang] ?? strings["zh-CN"] ?? {};
}
`;

writeFileSync(OUTPUT, output);
console.log(`Generated ${OUTPUT} with ${langs.length} languages: ${langs.join(", ")}`);
console.log(`  ${keys.length} string keys`);
