import { readFileSync, writeFileSync, readdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const LOCALES_DIR = join(ROOT, "locales");
const OUTPUT = join(ROOT, "src", "strings.ts");

const files = readdirSync(LOCALES_DIR).filter(f => f.endsWith(".json"));
const all = {};
const languages = [];

for (const file of files) {
	const lang = file.replace(".json", "");
	const content = JSON.parse(readFileSync(join(LOCALES_DIR, file), "utf-8"));
	const meta = content["$meta"] || {};
	languages.push({ code: lang, name: meta.language_name || lang });
	const { $meta, ...strings } = content;
	all[lang] = strings;
}

const sortedLangs = languages.sort((a, b) => a.code.localeCompare(b.code));
const langs = Object.keys(all);
const keys = Object.keys(all[langs[0]]);
const langUnion = langs.map(l => `"${l}"`).join(" | ");

const languagesArray = JSON.stringify(sortedLangs, null, 2);

let output = `// Auto-generated by scripts/generate-strings.mjs. Do not edit.
// Run \`npm run build:strings\` to regenerate.

export interface LanguageInfo {
  code: string;
  name: string;
}

const strings: Record<string, Record<string, string>> = ${JSON.stringify(all, null, 2)};

export const LANGUAGES: LanguageInfo[] = ${languagesArray};

export type Lang = ${langUnion};

export function t(key: string, lang: Lang): string {
  return strings[lang]?.[key] ?? strings["zh-CN"]?.[key] ?? key;
}

export function langStrings(lang: Lang): Record<string, string> {
  return strings[lang] ?? strings["zh-CN"] ?? {};
}
`;

writeFileSync(OUTPUT, output);
console.log(`Generated ${OUTPUT} with ${langs.length} languages: ${langs.join(", ")}`);
console.log(`  ${keys.length} string keys`);
